version: "3"

services:
  db:
    container_name: mysql_dev
    image: mysql:latest
    restart: always
    volumes:
      - sql-data:/var/lib/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorial
    ports:
      - "3100:3306"
    networks:
      - backend
volumes:
  sql-data:

networks:
  backend:
